[package]
name = "bot"
version = "0.1.0"
authors = ["plaets"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serenity]
default-features = true
version = "0.8"
